exports.APP = {
    SHOW_APP_CLOSE_MODAL:'SHOW_APP_CLOSE_MODAL',
    HIDE_APP_CLOSE_MODAL:'HIDE_APP_CLOSE_MODAL'
};
exports.ROUTES = {
    LOAD_INITIAL_ROUTES_DATA:'LOAD_INITIAL_ROUTES_DATA'
};
exports.VEHICLES = {
    LOAD_INITIAL_VEHICLES_DATA:'LOAD_INITIAL_VEHICLES_DATA'
};
